### PR TITLE
[16.0][IMP] sale_global_discount: calculate lines with fixed taxes should be based on product uom qty

### PR DESCRIPTION
**Pull request by QuocDuong1306**
Context:
- The taxes with `fixed` type should be matched with [native odoo](https://github.com/odoo/odoo/blob/223d0d57e9ff12145ba2b95041c8fc62eacb3b88/addons/account/models/account_tax.py#L359)
- BTW, I added one commit to update `test-requirement.txt`

It would be nice if the PR was merged

### CODE REVIEW

**Review by santostelmo — APPROVED** [review]

**Review by cyrilmanuel — APPROVED** [review]
not an expert but LGTM


Could you change the origin of the branch from studio73 to OCA --> Because the original PR was merged already --> https://github.com/OCA/sale-workflow/pull/2343

**Comment by trisdoan** [comment]
Hello @QuocDuong1306, I prepared https://github.com/OCA/sale-workflow/pull/321. You can close this one

**Comment by cyrilmanuel** [comment]
Hello @QuocDuong1306 , @trisdoan  thanks a lot for your work :) just to be sure, the link point on a wrong PR i think it's for the PR 3216.  That's mean you have merge the pull 1 and 2 on one pr in sale-workflow ??

**Comment by trisdoan** [comment]
Hi, yeah silly me, you're right, both of them are included

**Pull request closed without merging**
